handlers:
  - sink: ext://sys.stderr
    format: "<level>{level: <8}</level>| <magenta>{name}</magenta>:<bold>{function}</bold>:<magenta>{line}</magenta> |  <level>{message}</level> | <l>{extra}</>"
  - sink: ./logs/file.log
    enqueue: true
    serialize: true
# levels:
#   - name: NEW
#     'no': 13
#     icon: ¤
#     color: ""
extra:
  env: env://APP_ENV
activation:
  - ["my_module.secret", false]
  - ["another_library.module", true]
