handlers:
  - sink: ext://sys.stderr
    format: "<level>{level: <8}</level>| <magenta>{name}</magenta>:<bold>{function}</bold>:<magenta>{line}</magenta> |  <level>{message}</level> | <l>{extra}</>"

extra:
  env: "override me please"

activation:
  - ["my_module.secret", false]
  - ["another_library.module", true]
